site/content/entry/texture-forwarding-brings-hd-output-to-citra.md
Now links to correct forum topic
=> Corrected forum ID

gulpfile.js
Because it doesn't look as nice :(
=> Disable image compression

site/themes/citra-bs-theme/layouts/game/list.html
Implemented the ability to filter games by their compatibility rating.
Gif:
=> Add compatibility filtering

site/themes/citra-bs-theme/layouts/game/list.html, site/themes/citra-bs-theme/static/css/style.css
This PR adds table sorting, it also changes the filtering to only search the compatibility column when clicking on a rating in the chart.
=> Search fixes and cleanup, sorting

site/themes/citra-bs-theme/layouts/game/list.html
After some digging, I've found some less documented (and not at all documented) List.js features that fix some issues. Also some general code improvements and fixes.
Also thanks to @chris062689 for helping me get Gulp set up, as it doesn't currently work on Windows.
=> Game compatibility list fixes and improvements

site/themes/citra-bs-theme/layouts/game/list.html
Fix regression introduced by #45/#46 which broke the chart filtering and the clear search button.
=> Fix scope errors

site/themes/citra-bs-theme/layouts/shortcodes/audio.html, site/themes/citra-bs-theme/layouts/shortcodes/video.html
Added some Hugo shortcodes to directly embed Ogg Vorbis audio and Ogg Theora video in Markdown.
=> Hugo Media Shortcodes

site/content/rules.md
The moderation rules have been updated, and this needs a rewrite to reflect the changes.
=> Rule update

scripts/games/app.js
Currently the rating displayed on the site is based off of the most recent test case.
This changes it to use a weighted average favoring younger test cases.
The test case's importance decays by 1/2 every month as illustrated by [this curve](https://www.desmos.com/calculator/th0iobng3a).
Before:
After:
=> Display weighted average of compatibility submissions

site/themes/citra-bs-theme/layouts/_default/baseof.html, site/themes/citra-bs-theme/layouts/partials/menu.html
=> Add links to Patreon, normalize baseof indentation

site/content/entry/citra-progress-report-2018-q2.md
* Fixes date to 20th September
=> Fix Date of Report Q2

site/themes/citra-bs-theme/layouts/game/single.html
=> Clarify the kind of date shown in game compat table

gulpfile.js
* Fixes an issue where browserSync errors out - when reloading, after changes have been saved.
cc @chris062689
=> Fix BrowserSync Error

site/themes/citra-bs-theme/layouts/game/list.html
* Removes "Add Game" button, as part of prep-work for the game DB update coming soon.
=> Remove "Add Game" button from the compatibility list

site/content/help/feature/game-modding.md
This article is based on yuzu's guide
Should not merge before citra-emu/citra#5088 is merged.
Example page: https://xenodochial-panini-758c13.netlify.com/help/feature/game-modding
=> Add game modding help article

site/content/help/feature/game-modding.md
Sorry for getting the Luma3DS mod format wrong. This fixes it.
(Anyway the website doesn't seem to be rebuilt yet)
Also since the format is so similar I will soon just add drop-in compatibility for Luma3DS mods.
=> Fix Luma3DS mod format

site/content/help/feature/multiplayer/index.md
https://github.com/citra-emu/citra-canary/blob/847c17b4469916ac9fb4fb75ec71ad7550b6c50b/src/dedicated_room/citra-room.cpp#L47
=> Update available cli arguments

site/content/entry/citra-progress-report-2020-q2.md
=> Fix blog post link.

.github/workflows/deploy.yml, package.json, yarn.lock
This Pull Request changes the current setup to a Yuzu-like setup.
Basically, build from `hugo` branch and push to `master` branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra-web/144)
=> ci: switch to Yuzu-like setup

site/themes/citra-bs-theme/layouts/game/list.html
Just a minor clarification that the results from the list are based on desktop results, not mobile
=> Small clarification

site/themes/citra-bs-theme/layouts/partials/menu.html
Adds missing content, corrects wording and spelling. 
Renames "Dev Wiki" to just "Wiki", as it's moved away from a developer only place.
=> layouts/partials: Edit navigation bar information
