citra-emu/citra-web

site/themes/citra-bs-theme/layouts/partials/jumbotron.html
This corrects the broken FAQ link on the homepage Jumbotron "Learn More"
=> Corrected 404 /wiki/FAQ link on Homepage

.travis.yml, gulpfile.js, scripts/downloads/.gitignore, scripts/downloads/app.js, scripts/downloads/license.txt, scripts/downloads/package.json, scripts/downloads/scripts/linux-bleeding.qs, scripts/downloads/scripts/linux-nightly.qs, scripts/downloads/scripts/msvc-bleeding.qs, scripts/downloads/scripts/msvc-nightly.qs, scripts/downloads/scripts/osx-bleeding.qs, scripts/downloads/scripts/osx-nightly.qs
(Do not merge)
This is the initial implementation of the Citra Web Qt repository builder. It polls releases in 'citra-emu/citra-nightly' and 'citra-emu/citra-bleeding-edge' and produces metadata based upon .7z files that it finds there.
This relies upon Cloudflare's redirects.
=> RFC: Generate Qt Installer Framework repositories

scripts/games/app.js
This now means that game wiki pages are handled independently of casing.
This fixes wiki pages not appearing on the rendered games articles.
=> Implement lookup table for wiki entries

site/themes/citra-bs-theme/static/js/renderDownloads.js
This avoids duplicate entries in the download UI.
=> Hide 7zip files from downloads UI

src/scss/citra-theme.scss
This unifies formatting in blog post tables and left aligns text in non-header columns.
This does, as far as I can see, affect current tables outside of blog entries.
=> Quickfix: Left align table cells by default

site/content/download.md, src/scss/citra-theme.scss
Do not merge - blocked by updater
======================
(Yes, Flame!)
Here we are. This PR includes a new downloads page with automatic detection of platforms for the updater (with a option to view other platforms, as well as the original downloads page). This also fixes Canary's titles in the download description.
=> RFC: New Downloads page

site/themes/citra-bs-theme/layouts/game/list.html
This fixes games like The Legend of Zelda being sorted under "T" instead of "L" on the compatibility list.
=> Remove the "The" prefix from titles in the data attribute

site/themes/citra-bs-theme/layouts/game/list.html, src/scss/citra-theme.scss
Fix regression introduced by #45/#46 that removed the section id headers ([see here](https://github.com/citra-emu/citra-web/pull/46/files#diff-0431ddf85bbf07fff323754f86096c3cL352)).
This also changes the title key from the first letter of the title to the proper section id.
See #32 for how it used to look like.
=> Re-add section id headers

site/themes/citra-bs-theme/layouts/shortcodes/callout.html
Example usage:
```markdown
{{% callout %}}
We're all terribly sorry for the delay in getting this progress
report out the door, but our main technical writer [anodium](https://github.com/anodium),
was just a bit busy surviving both Hurricane Irma and Maria. Although she's a
trooper and claims it's not an excuse for the delay, we find that her personal
safety is a tad more important. We're all glad that she's safe and sound, and in
a state where she can keep pumping out quality articles for Citra!
{{% /callout %}}
```
turns into:
=> Add callout for Hugo documents

scripts/games/app.js
Potential fix for test cases showing up in reverse order on game wiki pages, and the oldest test case being displayed as the most recent rating.
Ideally, Hugo would read the array backwards, but I couldn't find a way to do it. 
Closes citra-emu/citra-games-wiki#153
=> Reverse order of multiple test cases

README.md
Swap GraphicsMagick with ImageMagick on the list, since the wording on ImageMagick implies that it was meant to be listed afterwards.
=> Quickfix: Swap deps

scripts/games/package-lock.json, scripts/wiki/package-lock.json
Update `package-lock.json` to use sha512 hashes instead of sha1. Files generated by `gulp` installing dependencies automatically.
<https://shattered.io/>
=> Update package-lock.json files

.travis.yml
As per https://github.com/travis-ci/travis-ci/issues/9312, an upstream deploy bug relating to a broken Ruby gem has been fixed, and we are safe to remove the specific bugfix branch we were using previously, as introduced by https://github.com/citra-emu/citra-web/commit/3e2df0c726b3bfdeb58a58098a0388807535cfb2
=> Remove workaround for upstream GitHub pages deploy bug

site/content/help/_index.md, site/themes/citra-bs-theme/layouts/help/single.html, site/themes/citra-bs-theme/layouts/help/summary.html
This pull request improves the look of the user documentation:
- Wording of the index page has been improved, and now links to the appropriate pages. I've tried for [`ref` URLs](https://gohugo.io/content-management/cross-references/), but I wasn't able to get them to work for the developer wiki link, so I have made them both hardcoded links.
- The summaries of help pages now no longer include the default summary, because it didn't look good for them.
- The contents of the help pages are now rendered as blog entries so that they can benefit from blog CSS. One particular instance of this being useful is that text in figures in blog entries [are centered](https://github.com/citra-emu/citra-web/blob/master/src/scss/citra-theme.scss#L316-L319). I feel this is the best solution as the blog and …
=> Improve help pages

site/content/entry/citra-progress-report-2017-september.md, site/themes/citra-bs-theme/layouts/shortcodes/alert.html, site/themes/citra-bs-theme/layouts/shortcodes/callout.html, site/themes/citra-bs-theme/layouts/shortcodes/figure.html, site/themes/citra-bs-theme/layouts/shortcodes/sidebyside.html
Commit-by-commit review suggested.
This PR makes a few changes to the shortcodes:
- A new `alert` shortcode has been added, for future use with articles (both blogs, and help). `callout` has been removed, and the instance of it being used has been adjusted accordingly. This is what it looks like in action:
```md
{{% alert warning %}}
Ensure that you have the latest version of GodMode9 installed! Otherwise, odd issues may come up while dumping.
{{% /alert %}}
```
- The `figure` and `sidebyside` shortcodes now properly process Markdown in their captions.
- The `sidebyside` shortcode now has a `imagelink` mode, where an image can also be a clickable link. Here's an example showing off both this, and the last change:
```md
{{< sidebyside "imagelink" "/images/help/dumping/games/" …
```
=> Improve shortcodes

site/content/download.md
=> Display .7z files for Windows on the manual download page

site/content/help/feature/custom-textures/index.md
This is not WIP anymore. Also changed the language to make it more consistent with other help articles (starting with something like `Citra can ...`)
=> Update Custom Textures help page to remove the WIP message

site/content/help/feature/multiplayer/index.md
Lists need to be surrounded by blank lines. For this reason, previously they weren't properly displayed.
Tested on netlify and verified that it now works.
However tables are still missing borders.
=> Fix multiplayer help page

package.json, yarn.lock
This PR is an attempt to fix the current issues with our website CI.
Changes include:
* modify `citra-web` npm package's repository field to contain VALID SPDX LICENSE.
* update the existing `yarn.lock` to bring parity with changes to `package.json` and `package-lock.json`
=> Fix CI issues

site/content/help/feature/game-modding.md
Thanks to citra-emu/citra#5110, we now have drop-in compatibility with Luma3DS mods. Update the help document to reflect that.
=> Update game modding article to reflect drop-in compatibility with Luma mods

package.json, scripts/games/package.json, scripts/games/yarn.lock, scripts/wiki/package.json, scripts/wiki/yarn.lock, site/content/download.md, yarn.lock
This pull request changes the Linux download to point to the FlatHub Citra page. Also there are some basic maintenance updates to the Javascript dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra-web/149)
=> Switch Linux download to FlatHub

site/content/download.md
Since there are M2 chipsets as well now, and ofcourse we've already had someone on the forums say that they didn't think the notice applied to them since it said "M1", and not "M2". ~~Makes me wonder if I should specifically mention M1 and M2 as well...~~
I included it.
=> Update the Apple silicon notice

site/themes/citra-bs-theme/layouts/entry/single.html
Recently, Discourse changed the URLs for accounts from sitename.com/users/user to sitename.com/u/user
This PR just edits the single.html file to ensure that the Discourse accounts of the authors of the blog posts can still be accessed. At the moment, it just returns an error stating "That page doesn’t exist or is private".
=> Edit single.html to reflect Discourse account changes

site/assets/scss/citra-theme.scss
At the moment, the font size is just a little too big for the Mega Progress Reports, to the point where it starts cutting off the banner and looking weird. 
This is fixed by changing the size from 48px to 46px (number suggested by liushuyu on Discord a few weeks back)
=> Change font size for blog post entry headers.

site/content/download.md
Changes "Android Build" to "Google Play Store Build".
Clears up some confusion surrounding the fact that the Canary and Nightly builds also have Android builds for download on the same page now.
=> Small correction on the Downloads page

site/content/download.md
Now that Vulkan is added to Canary, Apple Silicon (M1/M2) devices work in Citra. This notice is now redundant.
=> Remove Apple Silicon notice from downloads page

site/assets/js/download.js
Fixes https://github.com/citra-emu/citra-web/issues/187.
=> download: Use correct icon for macos build

site/content/download.md
* Updates the download links to point to the refreshed builds of the installer using the latest QtIFW.
* Updates the Linux link to point to the Qt installer for the AppImage.
* Updates the wording of the macOS download since we have universal builds of Citra now.
=> download: Update installer links.
